// Generated by https://quicktype.io

export interface LoginResponse {
    nickname: string;
    email:    string;
    avatar:   string;
    token:    string;
    role:     string;
}

// Generated by https://quicktype.io

export class LoginDto {
    email:    string;
    password: string;

    constructor(){
        this.email = '';
        this.password = '';
    }
}

